-- VetFlow - Test Baseline for H2
-- Solo lo necesario para Owner/Patient + constraints usadas en los tests

-- OWNERS
CREATE TABLE owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PATIENTS
CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    species VARCHAR(50) NOT NULL,
    breed VARCHAR(100),
    birth_date DATE,
    weight DECIMAL(5,2),
    allergies TEXT,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_patient_owner
        FOREIGN KEY (owner_id) REFERENCES owners(id)
        ON DELETE RESTRICT,

    -- lo que necesitamos para el test que espera DataIntegrityViolationException
    CONSTRAINT chk_positive_weight CHECK (weight > 0)
);

CREATE INDEX idx_patients_owner_id ON patients(owner_id);
CREATE INDEX idx_owners_email ON owners(email);
